name: Deploy PRO
on:
  issues:
    types: [opened,edited]


jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  printData:    
    name: Print label
    runs-on: ubuntu-latest
    steps:
    - name: print Labels
      run: |
        echo ${{github.event.issue.labels.*.name}}
    - name: Extract tag from comment
      id: extract_tag
      run: echo "::set-output name=tag::$(echo ${{ github.event.issue.body }} | grep -oP 'tag:\K(\d*-).*' )"
    - name: Verify if tag exists
      run: |
        if git rev-parse --quiet --verify ${{ steps.extract_tag.outputs.tag }} >/dev/null; then
          echo "Tag exists"
        else
          echo "Tag does not exist"
          exit 1
        fi
