name: Deploy PRO
on:
  issues:
    types: [opened,edited]


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: echo tags
      run: echo  "I have many tags" {{github.event.issue.labels.name}}
    
