name: Deploy PRO
on:
  issues:
    types: [opened,edited]


jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  printLabels:    
    name: Print label
    runs-on: ubuntu-latest
    steps:
    - name: print Labels
      run: |
        echo ${{github.event.issue.labels.*.name}}
        
