name: Deploy PRO
on:
  issues:
    types: [opened,edited]


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: echo event
      run: |
        echo ${{github.event.issue.number}}
        echo ${{github.event.issue}}
        
