name: Sync Fork

on:
  schedule:
    - cron: '0 0 1 * *'  # At 00:00 on day-of-month 1.
  workflow_dispatch:  # Allows manual triggering
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token:  ${{ github.token }}

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/demisto/content.git  
        git fetch upstream

    - name: Create Branch and pull changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git checkout -b updates/upstream
        git pull upstream master --no-rebase
      
    - name: Create Pull Request
      run: |
        gh pr create -R laurasfo/demisto-content -B master --head updates/upstream -t "Merge upstream changes" --body "This PR merges the latest changes from the upstream repository."
        